# Python OOP (June 15, 2024)

# 1. Write a class to implement Softmax and Softmax stable

In [ ]:
import torch

In [ ]:
class Softmax(torch.nn.Module):
    def __init__(self) -> None:
        super(Softmax, self).__init__()
        self.eval()

    def forward(self, x) -> torch.Tensor:
        # Re-factor: return torch.nn.functional.softmax(x, dim=0)
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x, dim=0)
        return exp_x / sum_exp_x


class SoftmaxStable(torch.nn.Module):
    def __init__(self) -> None:
        super(SoftmaxStable, self).__init__()
        self.eval()

    def forward(self, x) -> torch.Tensor:
        c = torch.max(x)
        exp_x_c = torch.exp(x-c)
        sum_exp_x_c = torch.sum(exp_x_c, dim=0)
        return exp_x_c / sum_exp_x_c

In [ ]:
data = torch.Tensor([1, 2, 3])
softmax = Softmax()
output = softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
data = torch.Tensor([5, 2, 4])
softmax = Softmax()
output = softmax(data)
output

tensor([0.7054, 0.0351, 0.2595])

In [ ]:
data = torch.Tensor([1, 2, 300000000])
softmax = Softmax()
output = softmax(data)
output

tensor([0., 0., nan])

In [ ]:
data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
output

tensor([0.0900, 0.2447, 0.6652])

## 2. Một Ward (phường) gồm có name (string) và danh sách của mọi người trong Ward. Một người person có thể là student, doctor, hoặc teacher. Một student gồm có name, yob (int) (năm sinh), và grade (string). Một teacher gồm có name, yob, và subject (string). Một doctor gồm có name, yob, và specialist (string). Lưu ý cần sử dụng a list để chứa danh sách của mọi người trong Ward.

### (a) Cài đặt các class Student, Doctor, và Teacher theo mô tả trên. Thực hiện phương thức describe() method để in ra tất cả thông tin của các object

In [ ]:
from abc import abstractmethod, ABC

In [ ]:
class Person(ABC):
    def __init__(self, name, yob) -> None:
        self._name = name
        self._yob = yob

    @property
    def name(self) -> str:
        return self._name

    @property
    def yob(self) -> int:
        return self._yob

    @abstractmethod
    def describe(self) -> None:
        pass


class Student(Person):
    def __init__(self, name, yob, grade) -> None:
        super(Student, self).__init__(name, yob)
        self._grade = grade

    @property
    def grade(self) -> str:
        return self._grade

    def describe(self) -> None:
        print(
            f"Student - Name : {self._name} - YoB: {self._yob} - Grade : {self._grade}")


class Teacher(Person):
    def __init__(self, name, yob, subject) -> None:
        super(Teacher, self).__init__(name, yob)
        self._subject = subject

    @property
    def subject(self) -> str:
        return self._subject

    def describe(self) -> None:
        print(
            f"Teacher - Name : {self._name} - YoB: {self._yob} - Subject : {self._subject}")


class Doctor(Person):
    def __init__(self, name, yob, specialist) -> None:
        super(Doctor, self).__init__(name, yob)
        self._specialist = specialist

    @property
    def specialty(self) -> str:
        return self._specialist

    def describe(self) -> None:
        print(
            f"Doctor - Name : {self._name} - YoB: {self._yob} - Specialty : {self._specialist}")

In [ ]:
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()

Student - Name : studentA - YoB: 2010 - Grade : 7


In [ ]:
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()

Teacher - Name : teacherA - YoB: 1969 - Subject : Math


In [ ]:
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()

Doctor - Name : doctorA - YoB: 1945 - Specialty : Endocrinologists


### (b) Viết add_person(person) method trong Ward class để add thêm một người mới với nghề nghiệp bất kỳ (student, teacher, doctor) vào danh sách người của ward. Tạo ra một ward object, và thêm vào 1 student, 2 teacher, và 2 doctor. Thực hiện describe() method để in ra tên ward (name) và toàn bộ thông tin của từng người trong ward.

In [ ]:
class Ward:
    def __init__(self, name) -> None:
        self._people = []
        self._name = name

    def describe(self) -> None:
        print(f"Ward Name: {self._name}")
        for person in self._people:
            person.describe()

    # 2b. Add a person to the ward
    def add_person(self, person: Person) -> None:
        self._people.append(person)

    # 2c. Count the number of doctors in the ward
    def count_doctor(self) -> int:
        return len([person for person in self._people if isinstance(person, Doctor)])

    # 2d. Sort age of people in the ward in an increasing order
    def sort_age(self) -> None:
        self._people.sort(key=lambda x: x._yob, reverse=True)

    # 2e. Calculate the average age of teachers in the ward:
    def compute_average(self) -> float:
        teachers = [
            person for person in self._people if isinstance(person, Teacher)]
        return sum([teacher.yob for teacher in teachers]) / len(teachers)

In [ ]:
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward 1")
ward1 = Ward(name=" Ward1 ")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

Ward Name:  Ward1 
Student - Name : studentA - YoB: 2010 - Grade : 7
Teacher - Name : teacherA - YoB: 1969 - Subject : Math
Teacher - Name : teacherB - YoB: 1995 - Subject : History
Doctor - Name : doctorA - YoB: 1945 - Specialty : Endocrinologists
Doctor - Name : doctorB - YoB: 1975 - Specialty : Cardiologists


### (c) Viết count_doctor() method để đếm số lượng doctor trong ward.

In [ ]:
print(f"Number of doctors: {ward1.count_doctor()}")

Number of doctors: 2


### (d) Viết sort_age() method để sort mọi người trong ward theo tuổi của họ với thứ tự tăng dần. (hint: Có thể sử dụng sort của list hoặc viết thêm function đều được)

In [ ]:
print(f"After sorting Age of Ward1 people")
ward1.sort_age()
ward1.describe()

After sorting Age of Ward1 people
Ward Name:  Ward1 
Student - Name : studentA - YoB: 2010 - Grade : 7
Teacher - Name : teacherB - YoB: 1995 - Subject : History
Doctor - Name : doctorB - YoB: 1975 - Specialty : Cardiologists
Teacher - Name : teacherA - YoB: 1969 - Subject : Math
Doctor - Name : doctorA - YoB: 1945 - Specialty : Endocrinologists


### (e) Viết compute_average() method để tính trung bình năm sinh của các teachers trong ward

In [ ]:
print(f"Average year of birth (teachers): {ward1.compute_average()}")

Average year of birth (teachers): 1982.0


## 3. Thực hiện xây dựng class Stack với các phương thức (method) sau đây

![MyStack](stack.png)

In [ ]:
class MyStack:
    def __init__(self, capacity: int) -> None:
        self._data = []
        self._capacity = capacity

    def is_empty(self) -> bool:
        return len(self._data) == 0

    def is_full(self) -> bool:
        return len(self._data) == self._capacity

    def pop(self):
        if self.is_empty():
            raise Exception("Stack is empty")
        return self._data.pop()

    def push(self, value):
        if self.is_full():
            raise Exception("Stack is full")
        self._data.append(value)

    def top(self):
        if self.is_empty():
            raise Exception("Stack is empty")
        return self._data[-1]

In [ ]:
stack1 = MyStack(capacity=5)

In [ ]:
stack1.push(1)
stack1.push(2)
print(stack1.is_full())

False


In [ ]:
print(stack1.pop())

2


In [ ]:
print(stack1.top())

1


In [ ]:
print(stack1.pop())

1


In [ ]:
print(stack1.is_empty())

True


## 4. Thực hiện xây dựng class Queue với các chức năng (method) sau đây

![MyQueue](queue.png)

In [ ]:
class MyQueue:
    def __init__(self, capacity: int) -> None:
        self._data = []
        self._capacity = capacity

    def is_empty(self) -> bool:
        return len(self._data) == 0

    def is_full(self) -> bool:
        return len(self._data) == self._capacity

    def dequeue(self):
        if self.is_empty():
            raise Exception("Queue is empty")
        return self._data.pop(0)

    def enqueue(self, value):
        if self.is_full():
            raise Exception("Queue is full")
        self._data.append(value)

    def front(self):
        if self.is_empty():
            raise Exception("Queue is empty")
        return self._data[0]

In [ ]:
queue1 = MyQueue(capacity=5)

In [ ]:
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.is_full())

False


In [ ]:
print(queue1.front())

1


In [ ]:
print(queue1.dequeue())

1


In [ ]:
print(queue1.front())

2


In [ ]:
print(queue1.dequeue())

2


In [ ]:
print(queue1.is_empty())

True
